import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <head>
        <ThemeModeScript />
      </head>
      <body className="bg-white text-gray-600 antialiased dark:bg-gray-900 dark:text-gray-400">
        {children}
      </body>
    </html>
  );
}
